### ISSUE TITLE
Is there a way to turn off the bracket optimisation? I would like to save a formula in the format of x/(n*n)

### ISSUE THREAD

**Issue by ststaynov** [KennethanCeyer/metric-parser#11]

**Comment by KennethanCeyer** [comment]
Humm.. it is not expected optimization things..

This is just bug of the optimization plan

It's needed to fix ASAP as next plan

**Comment by KennethanCeyer** [comment]
**INPUT**
```javascript
metricParser.convert('1 / (2 * 3)')
```

```json
{
   "operator":"/",
   "operand1":{
      "value":{
         "type":"unit",
         "unit":1
      }
   },
   "operand2":{
      "operator":"*",
      "operand1":{
         "value":{
            "type":"unit",
            "unit":2
         }
      },
      "operand2":{
         "value":{
            "type":"unit",
            "unit":3
         }
      }
   }
}
```

**TRY**
```javascript
const input = /* the above json file */;
metricParser.convert(input);
```

**EXPECTED**
```javacript
1 / ( 2 * 3 )
```

**ACTUALLY**
```javascript
1 / 2 * 3
```

**CONCLUSION**
```plaintext
The bracket which uses same level operator flat,
An optimizor deletes that bracket when unparsing process
```

**Comment by KennethanCeyer** [comment]
This issue will be handled within 5 days

If you are interested in contributing,
you can contribute by referring to the above.

**Comment by KennethanCeyer** [comment]
This issue will be handled soon (It seems to take long 😢 )

If @ststaynov, You are interested in contributing,
you can contribute by referring to the above.

**Comment by ststaynov** [comment]
@KennethanCeyer unfortunately I don't think I have what it takes to dive and contribute into such a project. That being said do you have a time/plan for this repo and when this bug could be fixed? I'd love to integrate it in my project!

**Comment by KennethanCeyer** [comment]
@ststaynov 

I understand your point and I apologize that I can't solve this issue quickly.

This issue is very important to me, I already know this is.
(This library belongs https://github.com/KennethanCeyer/formulize as a dependency)

So this issue is on top of my job list.

**Comment by ststaynov** [comment]
@KennethanCeyer do you think it could be solved in a week or two? Or will it take more time?

**Comment by KennethanCeyer** [comment]
@ststaynov 

I try to fix this issue in this weeks

I already had tried to fix this issue, This issue is not difficult to fix but...

Typescript with UMD + Test occurred some error message(build error)

I think it is related to nyc(Istanbul) 

So i will change coverage tool in this week 

This is main point in this issue (yak shaving)

**Comment by KennethanCeyer** [comment]
@ststaynov 

This issue is related a follows codes

https://github.com/KennethanCeyer/metric-parser/blob/10c8333161cdfe131af10cd348c4b210552c6ce8/src/ast/ast.spec.ts#L28-L39

When above test code is passed, This issue is turned to `solved`

Thank you

**Comment by KennethanCeyer** [comment]
<img width="521" alt="2018-06-18 12 54 37" src="https://user-images.githubusercontent.com/7090315/41509663-362d0c42-7292-11e8-804c-32af3facd0aa.png">

This issue is solved, I will merge #12 PR within few minute 😄

**Comment by KennethanCeyer** [comment]
All good!

- npm published as `v0.0.12`
- git tagged as `v0.0.12`
- git pages published as `v0.0.12`

---

This issue is `solved`,

So this issue page will be closed within a week 

Thank you 😄

**Comment by ststaynov** [comment]
Great stuff! I tested it out and it works as expected 👍  Could you update the package.json of formulize so it uses the new "metric-parser@0.0.13" instead of "metric-parser@0.0.12"? Thanks!

**Comment by KennethanCeyer** [comment]
@ststaynov 

`metric-parser` latest version is `v0.0.12`

`formulize` is also updated to `v0.0.13`, That means are `formulize` already up-to-date `metric-parser` library 😄

**Comment by ststaynov** [comment]
My bad, I thought they had the same version numbering. Thanks again!
